### ISSUE TITLE
client coc abnormal exit with: 134

### ISSUE THREAD

**Issue by mhmdanas** [neoclide/coc-tsserver#111]
When opening Neovim to edit a ~TypeScript file~ any kind of file, about 70% or 80% of the time I get the following error:
```
client coc abnormal exit with: 134
```
Sometimes the exit code 139, and more rarely, 138 and 1.

I'm using a macOS 10.15.2 machine. Output of `nvim -v`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
Output of `CocOpenLog`:
```
2020-01-05T21:15:42.427 INFO (pid:21166) [services] - registered service "tsserver"
2020-01-05T21:15:42.456 INFO (pid:21166) [plugin] - coc 0.0.74-15f685206a initialized with node: v13.5.0
2020-01-05T21:15:42.485 INFO (pid:21166) [watchman] - watchman watching project: /Users/mhmdanas/Desktop/growthcalc-website
2020-01-05T21:15:42.517 INFO (pid:21166) [services] - service tsserver started
2020-01-05T21:15:43.709 INFO (pid:21166) [completion-complete] - Results from: around
2020-01-05T21:15:43.768 INFO (pid:21166) [services] - service tsserver started
2020-01-05T21:15:44.643 ERROR (pid:21166) [languages] - Source "tsserver-typescript" complete error: Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:133317:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136602:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136597:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140254:87)
    at IOSession.Session.getFileAndProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140237:29)
    at IOSession.Session.getCompletions (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140414:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:139397:61)
    at /Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140923:28)
    at IOSession.Session.executeCommand (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:33)
    at IOSession.Session.onMessage (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140955:35)
    at Interface.<anonymous> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:142270:27)
    at Interface.emit (events.js:305:20)
    at Interface._onLine (readline.js:323:10)
    at Interface._normalWrite (readline.js:468:12)
    at Socket.ondata (readline.js:180:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
    at TypeScriptServiceClient.dispatchResponse (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13454:30)
    at TypeScriptServiceClient.dispatchMessage (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13415:26)
    at Reader.callback (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13142:30)
    at Reader.onLengthData (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14400:22)
    at Socket.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14381:18)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
2020-01-05T21:15:44.645 INFO (pid:21166) [completion-complete] - Results from: around
2020-01-05T21:15:47.504 ERROR (pid:21166) [languages] - Source "tsserver-typescript" complete error: Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:133317:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136602:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136597:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140254:87)
    at IOSession.Session.getFileAndProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140237:29)
    at IOSession.Session.getCompletions (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140414:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:139397:61)
    at /Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140923:28)
    at IOSession.Session.executeCommand (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:33)
    at IOSession.Session.onMessage (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140955:35)
    at Interface.<anonymous> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:142270:27)
    at Interface.emit (events.js:305:20)
    at Interface._onLine (readline.js:323:10)
    at Interface._normalWrite (readline.js:468:12)
    at Socket.ondata (readline.js:180:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
    at TypeScriptServiceClient.dispatchResponse (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13454:30)
    at TypeScriptServiceClient.dispatchMessage (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13415:26)
    at Reader.callback (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13142:30)
    at Reader.onLengthData (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14400:22)
    at Socket.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14381:18)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
2020-01-05T21:15:49.089 ERROR (pid:21166) [languages] - Source "tsserver-typescript" complete error: Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:133317:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136602:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136597:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140254:87)
    at IOSession.Session.getFileAndProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140237:29)
    at IOSession.Session.getCompletions (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140414:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:139397:61)
    at /Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140923:28)
    at IOSession.Session.executeCommand (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:33)
    at IOSession.Session.onMessage (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140955:35)
    at Interface.<anonymous> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:142270:27)
    at Interface.emit (events.js:305:20)
    at Interface._onLine (readline.js:323:10)
    at Interface._normalWrite (readline.js:468:12)
    at Socket.ondata (readline.js:180:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
    at TypeScriptServiceClient.dispatchResponse (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13454:30)
    at TypeScriptServiceClient.dispatchMessage (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13415:26)
    at Reader.callback (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13142:30)
    at Reader.onLengthData (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14400:22)
    at Socket.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14381:18)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
2020-01-05T21:15:49.089 INFO (pid:21166) [completion-complete] - Results from: around
2020-01-05T21:15:50.894 ERROR (pid:21166) [languages] - Source "tsserver-typescript" complete error: Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:133317:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136602:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136597:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140254:87)
    at IOSession.Session.getFileAndProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140237:29)
    at IOSession.Session.getCompletions (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140414:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:139397:61)
    at /Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140923:28)
    at IOSession.Session.executeCommand (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:33)
    at IOSession.Session.onMessage (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140955:35)
    at Interface.<anonymous> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:142270:27)
    at Interface.emit (events.js:305:20)
    at Interface._onLine (readline.js:323:10)
    at Interface._normalWrite (readline.js:468:12)
    at Socket.ondata (readline.js:180:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
    at TypeScriptServiceClient.dispatchResponse (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13454:30)
    at TypeScriptServiceClient.dispatchMessage (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13415:26)
    at Reader.callback (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13142:30)
    at Reader.onLengthData (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14400:22)
    at Socket.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14381:18)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
2020-01-05T21:15:51.018 ERROR (pid:21166) [languages] - Source "tsserver-typescript" complete error: Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:133317:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136602:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:136597:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140254:87)
    at IOSession.Session.getFileAndProject (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140237:29)
    at IOSession.Session.getCompletions (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140414:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:139397:61)
    at /Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:88
    at IOSession.Session.executeWithRequestId (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140923:28)
    at IOSession.Session.executeCommand (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140932:33)
    at IOSession.Session.onMessage (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:140955:35)
    at Interface.<anonymous> (/Users/mhmdanas/Desktop/growthcalc-website/node_modules/typescript/lib/tsserver.js:142270:27)
    at Interface.emit (events.js:305:20)
    at Interface._onLine (readline.js:323:10)
    at Interface._normalWrite (readline.js:468:12)
    at Socket.ondata (readline.js:180:10)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
    at TypeScriptServiceClient.dispatchResponse (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13454:30)
    at TypeScriptServiceClient.dispatchMessage (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13415:26)
    at Reader.callback (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13142:30)
    at Reader.onLengthData (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14400:22)
    at Socket.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14381:18)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by mhmdanas** [comment]
I deleted the `~/.nvim` directory by mistake and that seems to have fixed the issue. I'll close this issue for now and reopen if it happens again
