### ISSUE TITLE
CocInstall coc-tsserver Failed

### ISSUE THREAD

**Issue by dawndiy** [neoclide/coc-tsserver#160]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/snap/node/2752/bin/node',
1 verbose cli   '/home/dawndiy/.node/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--ignore-scripts',
1 verbose cli   '--no-lockfile',
1 verbose cli   '--production'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.3.0
4 verbose npm-session e2165cc21df7f255
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall coc-tsserver@1.5.1
7 info lifecycle coc-tsserver@1.5.1~preinstall: coc-tsserver@1.5.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 12ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 200 https://registry.npm.taobao.org/@chemzqm%2ftsconfig 1647ms
18 http fetch GET 200 https://registry.npm.taobao.org/@chemzqm%2ftslint-config 1650ms
19 silly pacote range manifest for @chemzqm/tsconfig@^0.0.3 fetched in 1659ms
20 silly pacote range manifest for @chemzqm/tslint-config@^1.0.18 fetched in 1657ms
21 http fetch GET 200 https://registry.npm.taobao.org/vscode-languageserver-protocol 63ms
22 silly pacote range manifest for vscode-languageserver-protocol@^3.15.3 fetched in 70ms
23 http fetch GET 200 https://registry.npm.taobao.org/webpack 78ms
24 silly pacote range manifest for webpack@^4.42.1 fetched in 96ms
25 http fetch GET 200 https://registry.npm.taobao.org/vscode-languageserver-textdocument 83ms
26 silly pacote range manifest for vscode-languageserver-textdocument@^1.0.1 fetched in 86ms
27 http fetch GET 200 https://registry.npm.taobao.org/which 37ms
28 silly pacote range manifest for which@^2.0.2 fetched in 42ms
29 http fetch GET 200 https://registry.npm.taobao.org/typescript 138ms
30 silly pacote version manifest for typescript@3.8.3 fetched in 173ms
31 http fetch GET 200 https://registry.npm.taobao.org/tslint-config-prettier 74ms
32 silly pacote range manifest for tslint-config-prettier@^1.6.0 fetched in 77ms
33 http fetch GET 200 https://registry.npm.taobao.org/tslint-react 74ms
34 silly pacote range manifest for tslint-react@^3.2.0 fetched in 80ms
35 http fetch GET 200 https://registry.npm.taobao.org/vscode-jsonrpc 65ms
36 silly pacote range manifest for vscode-jsonrpc@^5.0.1 fetched in 71ms
37 http fetch GET 200 https://registry.npm.taobao.org/vscode-languageserver-types 75ms
38 silly pacote version manifest for vscode-languageserver-types@3.15.1 fetched in 79ms
39 http fetch GET 200 https://registry.npm.taobao.org/@webassemblyjs%2fast 33ms
40 silly pacote version manifest for @webassemblyjs/ast@1.9.0 fetched in 43ms
41 http fetch GET 200 https://registry.npm.taobao.org/@webassemblyjs%2fhelper-module-context 29ms
42 silly pacote version manifest for @webassemblyjs/helper-module-context@1.9.0 fetched in 33ms
43 http fetch GET 200 https://registry.npm.taobao.org/@types%2fnode 2445ms
44 http fetch GET 200 https://registry.npm.taobao.org/@types%2ffast-diff 2459ms
45 silly pacote range manifest for @types/node@^13.11.1 fetched in 2463ms
46 silly pacote range manifest for @types/fast-diff@^1.2.0 fetched in 2467ms
47 warn deprecated @types/fast-diff@1.2.0: This is a stub types definition. fast-diff provides its own type definitions, so you do not need this installed.
48 http fetch GET 200 https://registry.npm.taobao.org/@webassemblyjs%2fwasm-edit 32ms
49 verbose stack Error: EACCES: permission denied, write
49 verbose stack     at writeSync (fs.js:694:3)
49 verbose stack     at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
49 verbose stack     at writeOrBuffer (_stream_writable.js:352:12)
49 verbose stack     at SyncWriteStream.Writable.write (_stream_writable.js:303:10)
49 verbose stack     at EventEmitter.log.write (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:271:10)
49 verbose stack     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:234:12)
49 verbose stack     at Array.forEach (<anonymous>)
49 verbose stack     at EventEmitter.log.emitLog (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:232:28)
49 verbose stack     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:214:8)
49 verbose stack     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:286:23)
49 verbose stack     at deprCheck (/home/dawndiy/.node/lib/node_modules/npm/lib/utils/depr-check.js:18:11)
49 verbose stack     at /home/dawndiy/.node/lib/node_modules/npm/lib/fetch-package-metadata.js:66:33
49 verbose stack     at tryCatcher (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
49 verbose stack     at Promise._settlePromiseFromHandler (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
49 verbose stack     at Promise._settlePromise (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
49 verbose stack     at Promise._fulfillPromises (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:674:14)
50 verbose cwd /tmp/coc-tsserver-caRT26
51 verbose Linux 5.4.0-33-generic
52 verbose argv "/snap/node/2752/bin/node" "/home/dawndiy/.node/bin/npm" "install" "--ignore-scripts" "--no-lockfile" "--production"
53 verbose node v14.3.0
54 verbose npm  v6.14.5
55 error code EACCES
56 error syscall write
57 error errno -13
58 error Error: EACCES: permission denied, write
58 error     at writeSync (fs.js:694:3)
58 error     at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
58 error     at writeOrBuffer (_stream_writable.js:352:12)
58 error     at SyncWriteStream.Writable.write (_stream_writable.js:303:10)
58 error     at EventEmitter.log.write (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:271:10)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:234:12)
58 error     at Array.forEach (<anonymous>)
58 error     at EventEmitter.log.emitLog (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:232:28)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:214:8)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:286:23)
58 error     at deprCheck (/home/dawndiy/.node/lib/node_modules/npm/lib/utils/depr-check.js:18:11)
58 error     at /home/dawndiy/.node/lib/node_modules/npm/lib/fetch-package-metadata.js:66:33
58 error     at tryCatcher (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
58 error     at Promise._settlePromiseFromHandler (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
58 error     at Promise._settlePromise (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
58 error     at Promise._fulfillPromises (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:674:14)
58 error  Error: EACCES: permission denied, write
58 error     at writeSync (fs.js:694:3)
58 error     at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
58 error     at writeOrBuffer (_stream_writable.js:352:12)
58 error     at SyncWriteStream.Writable.write (_stream_writable.js:303:10)
58 error     at EventEmitter.log.write (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:271:10)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:234:12)
58 error     at Array.forEach (<anonymous>)
58 error     at EventEmitter.log.emitLog (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:232:28)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:214:8)
58 error     at EventEmitter.<anonymous> (/home/dawndiy/.node/lib/node_modules/npm/node_modules/npmlog/log.js:286:23)
58 error     at deprCheck (/home/dawndiy/.node/lib/node_modules/npm/lib/utils/depr-check.js:18:11)
58 error     at /home/dawndiy/.node/lib/node_modules/npm/lib/fetch-package-metadata.js:66:33
58 error     at tryCatcher (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
58 error     at Promise._settlePromiseFromHandler (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
58 error     at Promise._settlePromise (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
58 error     at Promise._fulfillPromises (/home/dawndiy/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:674:14) {
58 error   errno: -13,
58 error   syscall: 'write',
58 error   code: 'EACCES'
58 error }
59 error The operation was rejected by your operating system.
59 error It is likely you do not have the permissions to access this file as the current user
59 error
59 error If you believe this might be a permissions issue, please double-check the
59 error permissions of the file and its containing directories, or try running
59 error the command again as root/Administrator.
60 verbose exit [ -13, true ]

```

It said "write EACCES: permission denied", but I don't know where it can't be written to. Can you help me? Or is there any method I can install it as a coc.nvim extension manually.

**Comment by chemzqm** [comment]
Read wiki of coc.nvim

**Comment by dawndiy** [comment]
@chemzqm I've read it, but can't find a method to fix my issue.
I found the reason for failure in my scene. If your node installed by snap, it will fail to install coc-tsserver using :CocInstall . And the node installed by APT will success.
