### ISSUE TITLE
this.fileExistsWithCache is not a function coc-tsserver 1.5.3

### ISSUE THREAD

**Issue by linde12** [neoclide/coc-tsserver#183]
Hi, trying to run CodeActionAsync and i'm sometimes i'm getting the following error

```
[coc.nvim]: Error on notification "codeAction": Error processing request. this.fileExistsWithCache is not a function
TypeError: this.fileExistsWithCache is not a function
    at Object.Project.fileExists (/mnt/my/repo/node_modules/typescript/lib/tsserver.js:134638:29)
    at Object.ConfiguredProject.fileExists (/mnt/my/repo/node_modules/typescript/lib/tsserver.js:135753:49)
    at tryGetModuleNameAsNodeModule (/mnt/my/repo/node_modules/typescript/lib/tsserver.js:99539:43)
```

Using coc-tsserver 1.5.3 & latest coc.nvim (* e472c87 - (HEAD -> release, origin/release) fix(extensions): filter global extensions without version (78 minutes ago) <Qiming Zhao>)

Using typescript@3.7.5

**Comment by chemzqm** [comment]
Should be issue of your tsserver
