### ISSUE TITLE
using @types/jquery freezes neovim

### ISSUE THREAD

**Issue by TvrtkoM** [neoclide/coc-tsserver#248]
I'm not sure what's the problem but it only happens when auto-completing and displaying method documentation of jquery.

Neovim completely freezes for at least a minute. Annoying.

**Comment by TvrtkoM** [comment]
I tried inspecting with `:CocInfo` and I get this

```
2021-01-13T14:47:57.611 INFO (pid:22640) [plugin] - coc.nvim 0.0.80-fff2a86b16 initialized with node: v14.15.3 after 601ms
2021-01-13T14:48:03.133 INFO (pid:22640) [language-client-index] - eslint started with 23409
2021-01-13T14:48:03.248 INFO (pid:22640) [services] - registered service "tsserver"
2021-01-13T14:48:11.678 INFO (pid:22640) [completion-complete] - Results from: around
2021-01-13T14:48:15.437 INFO (pid:22640) [completion-complete] - Results from: file
2021-01-13T14:48:16.945 INFO (pid:22640) [completion-complete] - Results from: around,tsserver-typescript
2021-01-13T14:48:21.570 INFO (pid:22640) [completion-complete] - Results from: tsserver-typescript
2021-01-13T14:48:23.587 INFO (pid:22640) [completion-complete] - Results from: tsserver-typescript
2021-01-13T14:48:29.442 WARN (pid:22640) [events] - Handler of TextChangedI blocked more than 2s: Error
    at mq.on (/home/tvrtko/.vim/bundle/coc.nvim/build/index.js:133:216)
    at new IP (/home/tvrtko/.vim/bundle/coc.nvim/build/index.js:250:9995)
    at new OP (/home/tvrtko/.vim/bundle/coc.nvim/build/index.js:251:5526)
    at MP.init (/home/tvrtko/.vim/bundle/coc.nvim/build/index.js:254:5504)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/tvrtko/.vim/bundle/coc.nvim/build/index.js:129:13445
2021-01-13T14:49:04.594 INFO (pid:22640) [completion-complete] - Results from: around,tsserver-typescript
2021-01-13T14:49:38.614 INFO (pid:22640) [attach] - receive request: CocAutocmd [ 'BufWritePre', 3 ]
2021-01-13T14:49:38.619 INFO (pid:22640) [attach] - receive request: doAutocmd [ 1, 3 ]
2021-01-13T14:52:24.909 INFO (pid:22640) [attach] - receive notification: showInfo []
```

I don't know if it is relevant or no. 
What else can I do to see what's happening?

**Comment by chemzqm** [comment]
It's async, profile your vim for blocked function.
