### ISSUE TITLE
[coc.nvim] Error on rename: Error processing request. No Project.

### ISSUE THREAD

**Issue by silviubogan** [neoclide/coc-tsserver#253]
I am trying the `\rn` command.

```
[coc.nvim] Error on rename: Error processing request. No Project.
[coc.nvim] Error on rename: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:14960
9:23)
    at IOSession.Session.getProjects (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.
js:157374:42)
    at IOSession.Session.getRenameLocations (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/ts
server.js:157394:37)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/ty
pescript/lib/tsserver.js:156470:61)
    at /home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:158282:88
    at IOSession.Session.executeWithRequestId (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/
tsserver.js:158273:28)
    at IOSession.Session.executeCommand (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserv
er.js:158282:33)
    at IOSession.Session.onMessage (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js
:158306:35)
    at Interface.<anonymous> (/home/silviub/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:16051
6:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
```

The jsconfig.json is this:

```json
{
  "compilerOptions": {}
}
```

And the path of the file in the current Vim window relative to the jsconfig.json file is src/start-client.jsx.

If I delete the `jsconfig.json` file the error is gone and the rename popup appears.

If I make a test file at the root of the project the rename works well regardless of the `jsconfig.json` file.

**Comment by chemzqm** [comment]
Issue with tsserver, can't help
