### ISSUE TITLE
Connection to server got closed.  Server will not be restarted

### ISSUE THREAD

**Issue by tyetyetye** [neoclide/coc-tsserver#358]
After running :CocUpdate today I get this error when opening any .ts files:

Error: Connection to server got closed. Server will not be restarted.
    at xp.handleConnectionClosed (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:229:1006)
    at xp.handleConnectionClosed (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:229:29133)
    at t (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:229:386)
    at dN.invoke (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:34:9670)
    at hd.fire (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:34:10436)
    at gi (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:35:10897)
    at dN.invoke (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:34:9670)
    at hd.fire (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:34:10436)
    at FN.fireClose (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:34:12716)
    at ChildProcess.<anonymous> (/home/asdf/.local/share/nvim/plugged/coc.nvim/build/index.js:61:11975)

I reproduced error with minimal nvim configuration.  Only removing coc-tsserver stops error from occuring.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting
