### ISSUE TITLE
Debug Failure. False Expression when add type inside class that extends some function

### ISSUE THREAD

**Issue by axmad386** [neoclide/coc-tsserver#385]
I am not sure how to explain this. I got some Error when add some property inside class that extends some function. 
For example I have this code
```ts
class User extends Traitable(Model).use(Authenticatable, CrudTrait) {
  // this will make typescript happy
  static factory: () => any;
  username!: string;
  email!: string;
  password!: string;
  first_name!: string;
  last_name!: string;
  phone!: string;
  active!: boolean;

  public static fillable = [
    "username",
    "email",
    "password",
    "first_name",
    "last_name",
    "phone",
  ];
```
I want to add some property eg: `full_name!: string;` below `last_name`, then the error is thrown just after I type some character.
This is coc info result

```
## versions

vim version: NVIM v0.7.2
node version: v17.4.0
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /home/dmuggle/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-07-07T15:52:19.157 INFO (pid:166298) [coc-git] - Looking for git in: git
2022-07-07T15:52:19.314 INFO (pid:166298) [plugin] - coc.nvim initialized with node: v17.4.0 after 282ms
2022-07-07T15:52:22.541 INFO (pid:166298) [attach] - receive notification: showInfo []
2022-07-07T15:52:49.031 INFO (pid:166298) [services] - registered service "eslint"
2022-07-07T15:52:49.033 INFO (pid:166298) [services] - ESLint state change: stopped => starting
2022-07-07T15:52:49.086 INFO (pid:166298) [services] - registered service "tsserver"
2022-07-07T15:52:49.244 INFO (pid:166298) [services] - service tsserver started
2022-07-07T15:52:49.438 INFO (pid:166298) [services] - ESLint state change: starting => running
2022-07-07T15:52:49.447 INFO (pid:166298) [services] - service eslint started
2022-07-07T15:53:07.584 INFO (pid:166298) [attach] - receive notification: openList []
2022-07-07T15:53:09.440 INFO (pid:166298) [attach] - receive notification: openList [ 'extensions' ]
2022-07-07T15:53:38.970 ERROR (pid:166298) [node-client] - Error: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.setTextPos (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:12103:22)
    at Object.skipToEndOf (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:145432:25)
    at processChildNodes (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146927:47)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146844:21
    at visitNodes (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30474:24)
    at Object.forEachChild (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30665:21)
    at processNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146841:20)
    at processChildNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146912:21)
    at processChildNodes (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146966:48)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146844:21
    at visitNodes (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30474:24)
    at Object.forEachChild (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30653:24)
    at processNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146841:20)
    at processChildNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146912:21)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146842:21
    at visitNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30469:24)
    at Object.forEachChild (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:30628:21)
    at processNode (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146841:20)
    at formatSpanWorker (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146641:17)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146604:140
    at Object.getFormattingScanner (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:145231:23)
    at Object.formatNodeGivenIndentation (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:146604:31)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:132267:42
    at Object.flatMap (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:508:25)
    at Object.printAndFormatSnippetList (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:132265:34)
    at getEntryForMemberCompletion (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:132067:42)
    at createCompletionEntry (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:131887:23)
    at getCompletionEntriesFromSymbols (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:132394:29)
    at completionInfoFromData (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:131703:17)
    at Object.getCompletionsAtPosition (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:131558:36)
    at Object.getCompletionsAtPosition (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:164663:35)
    at IOSession.Session.getCompletions (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:176463:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:175138:61)
    at /home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:177195:88
    at IOSession.Session.executeWithRequestId (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:177186:28)
    at IOSession.Session.executeCommand (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:177195:33)
    at IOSession.Session.onMessage (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:177221:35)
    at Interface.<anonymous> (/home/dmuggle/GIT/lunox-backpack/node_modules/typescript/lib/tsserver.js:179826:31)
    at Interface.emit (node:events:520:28)
    at Interface.[_onLine] [as _onLine] (node:internal/readline/interface:389:12)
    at Interface.[_normalWrite] [as _normalWrite] (node:internal/readline/interface:574:59)
    at Socket.ondata (node:internal/readline/interface:219:23)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) Error
    at HM.echoError (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:35:1869)
    at MD.completeSource (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:33427)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async MD.completeSources (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:32178)
    at async MD.doComplete (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:31649)
    at async bte.startCompletion (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:43393)
    at async bte.triggerCompletion (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:47168)
    at async bte.onTextChangedI (/home/dmuggle/.vim/plugged/coc.nvim/build/index.js:277:45898)
2022-07-07T15:53:38.971 ERROR (pid:166298) [completion-complete] - Complete error: tsc-typescript Error: Error processing request. Debug Failure. False expression.
```
> **note**: this error is not thrown in vscode.

**Comment by axmad386** [comment]
Sorry, the problem actually is objection class. I use objection for ORM. Regular class not throwing this error.
