### ISSUE TITLE
The TypeScript service language died 5 times right after it got started

### ISSUE THREAD

**Issue by nicobross** [neoclide/coc-tsserver#387]
Hi, every time I open a javascript file I have the following error message and completion doesn't work well.

![image](https://user-images.githubusercontent.com/11701736/181392629-91255a66-f5f9-4fe9-8e45-b84e23308709.png)

and this is the error that I have in the coc-nvim.log

`2022-07-27T20:08:59.441 ERROR (pid:607510) [completion-complete] - Complete error: tsc-javascript Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at ForkedTsServerProcess.write (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13385:29)
    at TypeScriptServiceClient.sendRequest (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13913:28)
    at TypeScriptServiceClient.sendNextRequests (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13900:14)
    at TypeScriptServiceClient.executeImpl (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13893:10)
    at TypeScriptServiceClient.execute (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:13831:24)
    at /home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:9687:78
    at BufferSyncSupport.interuptGetErr (/home/bross/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:12500:14) {
  code: 'ERR_STREAM_DESTROYED'
}`

I know there is already an issue https://github.com/neoclide/coc-tsserver/issues/372 with this problem, but the solution was angular related, and I don't have angular installed in my computer. 

Could anyone please help me to tackle this issue?

**Comment by nicobross** [comment]
I've found that if I uninstall coc-clangd, tsserver starts working fine.

Does anyone happen to know why?

**Comment by chemzqm** [comment]
Could be not enough memory.

**Comment by chemzqm** [comment]
Tsserver crashed for some reason, checkout https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#troubleshooting or try lastest typescript module.

**Comment by chemzqm** [comment]
Should be issue with tsserver, use configuration `tsserver.tsdk` or command `:CocCommand tsserver.chooseVersion` to choose latest tsserver for your project.
