### ISSUE TITLE
Error output during import statement completion

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc-tsserver#394]
## Repro

**prepare**:

```
mkdir -p /tmp/sample
touch /tmp/sample/a.ts
cd /tmp/sample
nvim a.ts
```

**dummy.ts**:

> `|` is the cursor position.

Calling completion on a key to which `coc#refresh()` is mapped will output an error.

```typescript
import |
```

## DEMO

https://user-images.githubusercontent.com/188642/186121021-93a2c48b-065e-4050-878c-3dc900407bc2.mp4

## Error

```
[coc.nvim] Error: Error processing request. Cannot read properties of undefined (reading 'kind')
TypeError: Cannot read properties of undefined (reading 'kind')
    at Object.isTypeOnlyImportOrExportDeclaration (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/type
script/lib/tsserver.js:13228:22)
    at isTypeOnlyCompletion (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js
:133369:53)
    at getCompletionData (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:13
2945:38)
    at Object.getCompletionsAtPosition (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/
tsserver.js:131552:34)
    at Object.getCompletionsAtPosition (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/
tsserver.js:164663:35)
    at Proxy.<anonymous> (/Users/yaegassy/.config/coc/extensions/node_modules/coc-styled-components/node_modules/typescript-template-
language-service-decorator/lib/template-language-service-decorator.js:85:24)
    at IOSession.Session.getCompletions (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib
/tsserver.js:176463:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_mod
ules/typescript/lib/tsserver.js:175138:61)
    at /Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:177195:88
    at IOSession.Session.executeWithRequestId (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescri
pt/lib/tsserver.js:177186:28)
    at IOSession.Session.executeCommand (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib
/tsserver.js:177195:33)
    at IOSession.Session.onMessage (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsse
rver.js:177221:35)
    at Interface.<anonymous> (/Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.j
s:179826:31)
    at Interface.emit (node:events:513:28)
    at Interface._onLine (node:readline:491:10)
    at Interface._normalWrite (node:readline:665:12)
    at Socket.ondata (node:readline:272:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by chemzqm** [comment]
Happens on `/tmp` folder, avoid code in that folder.

**Comment by yaegassy** [comment]
This problem also occurs in other directories besides the `/tmp` directory

**Comment by chemzqm** [comment]
I've removed the echo, the error have to be fixed by typescript.

**Comment by yaegassy** [comment]
## Case2

The error is different, but completion with an import statement will also produce an error in this case.

### Repro 

> example for a react project.

**prepare**:

```
cd $HOME/src
npx create-react-app@latest react-check --template typescript
cd $HOME/src/react-check
nvim src/Check.tsx
```

## DEMO

https://user-images.githubusercontent.com/188642/186127628-abc9492a-8e95-4643-8552-25dc2863166e.mp4

## Error

```
[coc.nvim] Error: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at checkChangeRange (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:38559:26)
    at Object.updateSourceFile (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:38149:13)
    at Object.updateSourceFile (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:31160:47)
    at Object.updateLanguageServiceSourceFile (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:164223:40)
    at acquireOrUpdateDocument (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:135489:43)
    at Object.updateDocumentWithKey (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:135423:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsser
ver.js:164588:53)
    at tryReuseStructureFromOldProgram (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:117055:28)
    at Object.createProgram (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:116531:29)
    at synchronizeHostData (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:164475:26)
    at Proxy.getProgram (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:164607:13)
    at InferredProject.Project.updateGraphWorker (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:169675:53)
    at InferredProject.Project.updateGraph (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:169603:42)
    at Object.updateProjectIfDirty (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:171206:45)
    at InferredProject.Project.getLanguageService (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:169212:28)

    at IOSession.Session.getCompletions (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:176463:43)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:1
75138:61)
    at /Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:177195:88
    at IOSession.Session.executeWithRequestId (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:177186:28)
    at IOSession.Session.executeCommand (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:177195:33)
    at IOSession.Session.onMessage (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:177221:35)
    at Interface.<anonymous> (/Users/yaegassy/src/react-check/node_modules/typescript/lib/tsserver.js:179826:31)
    at Interface.emit (node:events:513:28)
    at Interface._onLine (node:readline:491:10)
    at Interface._normalWrite (node:readline:665:12)
    at Socket.ondata (node:readline:272:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by chemzqm** [comment]
You have to use master of coc.nvim.

**Comment by yaegassy** [comment]
> I've removed the echo, the error have to be fixed by typescript.

Thanks, problem solved. 🙇 https://github.com/neoclide/coc.nvim/commit/70837310a62c97fcb51ffa6be5e07547093145f5

**Comment by chemzqm** [comment]
You should use an auto pair plugin of vim or coc-paris, to avoid single`{`

**Comment by yaegassy** [comment]
Yes,  I usually use `jiangmiao/auto-pairs`, but I temporarily removed it because it might get in the way of reproducing this issue.
