### ISSUE TITLE
Getting 'No Project' error with 1.3.4 and 1.3.5

### ISSUE THREAD

**Issue by jason0x43** [neoclide/coc-tsserver#41]
With coc-tsserver verisons 1.3.4 and 1.3.5, tsserver can no longer see my TS project config. I've tried this with multiple TS projects. With both 1.3.4 and 1.3.5 I see streams of errors as shown below. Reverting to coc-tsserver 1.3.3 fixes the issue.

The `Definition not found` error was from me trying to jump to a symbol. The `Could not determine TypeScript or JavaScript project.` error was from me trying to execute `tsserver.goToProjectConfig`.

```
## versions

vim version: NVIM v0.4.0-dev
node version: v11.15.0
coc.nvim version: 0.0.69
term: Apple_Terminal
platform: darwin

## Messages[coc.nvim] Definition not found
[coc.nvim] Error on 'highlight': Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129786:29)
    at IOSession.Session.getDocumentHighlights (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129619:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129028:61)
    at /Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:307:10)
    at Interface._normalWrite (readline.js:448:12)
    at Socket.ondata (readline.js:164:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
[coc.nvim] Error on 'highlight': Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129786:29)
    at IOSession.Session.getDocumentHighlights (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129619:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129028:61)
    at /Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:307:10)
    at Interface._normalWrite (readline.js:448:12)
    at Socket.ondata (readline.js:164:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
[coc.nvim] Error on 'highlight': Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129786:29)
    at IOSession.Session.getDocumentHighlights (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129619:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129028:61)
    at /Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:307:10)
    at Interface._normalWrite (readline.js:448:12)
    at Socket.ondata (readline.js:164:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
[coc.nvim] Could not determine TypeScript or JavaScript project.
[coc.nvim] Error on 'highlight': Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129786:29)
    at IOSession.Session.getDocumentHighlights (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129619:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129028:61)
    at /Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:307:10)
    at Interface._normalWrite (readline.js:448:12)
    at Socket.ondata (readline.js:164:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
4 fewer lines

[coc.nvim] Error on 'highlight': Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129786:29)
    at IOSession.Session.getDocumentHighlights (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129619:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:129028:61)
    at /Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/Users/jason/Downloads/intern-lf-test/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:307:10)
    at Interface._normalWrite (readline.js:448:12)
    at Socket.ondata (readline.js:164:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
```

**Comment by chemzqm** [comment]
Looks like you have set `let b:coc_tsserver_disable =  1`

**Comment by jason0x43** [comment]
I'm not setting that myself anywhere, and as I said, if I downgrade to coc-tsserver@1.3.3, everything works properly. If I run `CocInstall coc-tsserver@1.3.4`, quit nvim, and then open the same TS file, I start seeing "No project" errors.

**Comment by chemzqm** [comment]
`:echo b:coc_tsserver_disable`

**Comment by jason0x43** [comment]
`E121: Undefined variable: b:coc_tsserver_disable`

**Comment by jason0x43** [comment]
That was with coc-tsserver 1.3.4, during a session that was generating the `No Project` errors.

**Comment by jason0x43** [comment]
It looks like the getVar call for tsserver_disable in bufferSyncSupport is generating an error:

`coc_nvim_1.workspace.getDocument(...).getVar is not a function`

**Comment by chemzqm** [comment]
The problem is coc.nvim is not latest version, should be fixed on coc-tsserver 1.3.6

**Comment by jason0x43** [comment]
Yeah, I just noticed that (that getVar was added in 0.7.0). Thanks for the quick response!

**Comment by noisyscanner** [comment]
For anyone in future, I found this was cause for me by having multiple `jsconfig.json` files in the monorepo. One at the repo root and one inside the package folder. I removed the one in the package folder and the error went away
