### ISSUE TITLE
Initialization failure

### ISSUE THREAD

**Issue by RobinClowers** [neoclide/coc-tsserver#440]
I'm just updated to the latest version, and the plugin seems to fail to load.

coc-tsserver version: 2.1.4
vim version: NVIM v0.9.1
node version: v18.15.0

In the `CocInfo` log I see the following.

```
2023-09-28T11:47:45.286 ERROR (pid:89139) [server] - unhandledRejection  Promise {
  <rejected> TypeError: value.toLowerCase is not a function
      at Object.fromString (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15654:28)
      at ServiceConfigurationProvider.readTsServerLogLevel (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15773:29)
      at ServiceConfigurationProvider.loadFromWorkspace (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15723:30)
      at new TypeScriptServiceClient (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:16535:61)
      at new TypeScriptServiceClientHost (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:17256:19)
      at TsserverService.start (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:17579:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: value.toLowerCase is not a function
    at Object.fromString (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15654:28)
    at ServiceConfigurationProvider.readTsServerLogLevel (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15773:29)
    at ServiceConfigurationProvider.loadFromWorkspace (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:15723:30)
    at new TypeScriptServiceClient (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:16535:61)
    at new TypeScriptServiceClientHost (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:17256:19)
    at TsserverService.start (/Users/robinclowers/dotfiles/config/coc/extensions/node_modules/coc-tsserver/lib/index.js:17579:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by chemzqm** [comment]
Seems you have bad configuration for `"tsserver.trace.server"`
