### ISSUE TITLE
version 2.2 not working on install

### ISSUE THREAD

**Issue by colinshr** [neoclide/coc-tsserver#463]
Reproduce not working:
- in gvim
  - CocInstall coc-tsserver

output:
2024-04-22T10:01:32.850 ERROR (pid:49388) [extensions] - Error on active extension coc-tsserver: import_coc50.services.register is not a function TypeError: import_coc50.services.register is not a function
    at Object.activate (~/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:17730:44)
    at ~/.vim/plugged/coc.nvim/build/index.js:265:1443
    at new Promise (<anonymous>)
    at Object.activate (~/.vim/plugged/coc.nvim/build/index.js:265:1401)
    at BF.activate (~/.vim/plugged/coc.nvim/build/index.js:262:7161)
    at ~.vim/plugged/coc.nvim/build/index.js:264:199
    at new Promise (<anonymous>)
    at s (~/.vim/plugged/coc.nvim/build/index.js:264:68)

Reproduce that works:
- in gvim
  - CocInstall coc-tsserver@2.1.4

CocInfo
vim version: VIM - Vi IMproved 9.0 9000472
node version: v18.17.0
coc.nvim version: 0.0.82-347e33d7 2022-09-09 18:16:50 +0800
coc.nvim directory: XXX/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.82-347e33d7 2022-09-09 18:16:50 +0800

Your coc.nvim was outdated, upgrade to latest release please.
