### ISSUE TITLE
ts-server fails when using diffview.nvim

### ISSUE THREAD

**Issue by pendar747** [neoclide/coc-tsserver#475]
Using `DiffviewOpen` from the https://github.com/sindrets/diffview.nvim in a typescript project produces this error and crashes tsserver

```
  <rejected> TypeScriptServerError: <semantic> TypeScript Server Error ([object Object])
  Debug Failure.
  Error: Debug Failure.
      at _ProjectService.updateNonInferredProjectFiles (/node_modules/typescript/lib/typescript.js:187453:34)
      at _ProjectService.addFilesToNonInferredProject (/node_modules/typescript/lib/typescript.js:187223:10)
      at _ProjectService.updateRootAndOptionsOfNonInferredProject (/node_modules/typescript/lib/typescript.js:187498:10)
      at _ProjectService.loadConfiguredProject (/node_modules/typescript/lib/typescript.js:187299:10)
      at _ProjectService.reloadConfiguredProject (/node_modules/typescript/lib/typescript.js:187548:10)
      at ConfiguredProject2.updateGraph (/node_modules/typescript/lib/typescript.js:185430:29)
      at updateWithTriggerFile (/node_modules/typescript/lib/typescript.js:185927:11)
      at updateConfiguredProject (/node_modules/typescript/lib/typescript.js:185935:9)
      at _ProjectService.findCreateOrReloadConfiguredProject (/node_modules/typescript/lib/typescript.js:188422:44)
      at _ProjectService.tryFindDefaultConfiguredProjectForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188446:25)
      at _ProjectService.tryFindDefaultConfiguredProjectAndLoadAncestorsForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188492:25)
      at _ProjectService.assignProjectToOpenedScriptInfo (/node_modules/typescript/lib/typescript.js:188377:27)
      at /node_modules/typescript/lib/typescript.js:188790:25
      at Array.forEach (<anonymous>)
      at _ProjectService.applyChangesInOpenFiles (/node_modules/typescript/lib/typescript.js:188788:56)
      at updateOpen (/node_modules/typescript/lib/typescript.js:189987:29)
      at /node_modules/typescript/lib/typescript.js:192655:15
      at IpcIOSession.executeWithRequestId (/node_modules/typescript/lib/typescript.js:192644:14)
      at IpcIOSession.executeCommand (/node_modules/typescript/lib/typescript.js:192653:29)
      at IpcIOSession.onMessage (/node_modules/typescript/lib/typescript.js:192701:68)
      at process.<anonymous> (/node_modules/typescript/lib/tsserver.js:525:14)
      at process.emit (node:events:519:28)
      at emit (node:internal/child_process:951:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
      at TypeScriptServerError.create (/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14264:12)
      at _ProcessBasedTsServer.dispatchResponse (/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14426:46)
      at _ProcessBasedTsServer.dispatchMessage (/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14369:18)
      at ChildProcess.<anonymous> (/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:14339:12)
      at ChildProcess.emit (node:events:519:28)
      at emit (node:internal/child_process:951:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
    serverId: 'semantic',
    version: TypeScriptVersion {
      path: '/node_modules/typescript/lib',
      _pathLabel: undefined,
      _api: [_API]
    },
    response: {
      seq: 0,
      type: 'response',
      command: 'updateOpen',
      request_seq: 23,
      success: false,
      message: 'Error processing request. Debug Failure.\n' +
        'Error: Debug Failure.\n' +
        '    at _ProjectService.updateNonInferredProjectFiles (/node_modules/typescript/lib/typescript.js:187453:34)\n' +
        '    at _ProjectService.addFilesToNonInferredProject (/node_modules/typescript/lib/typescript.js:187223:10)\n' +
        '    at _ProjectService.updateRootAndOptionsOfNonInferredProject (/node_modules/typescript/lib/typescript.js:187498:10)\n' +
        '    at _ProjectService.loadConfiguredProject (/node_modules/typescript/lib/typescript.js:187299:10)\n' +
        '    at _ProjectService.reloadConfiguredProject (/node_modules/typescript/lib/typescript.js:187548:10)\n' +
        '    at ConfiguredProject2.updateGraph (/node_modules/typescript/lib/typescript.js:185430:29)\n' +
        '    at updateWithTriggerFile (/node_modules/typescript/lib/typescript.js:185927:11)\n' +
        '    at updateConfiguredProject (/node_modules/typescript/lib/typescript.js:185935:9)\n' +
        '    at _ProjectService.findCreateOrReloadConfiguredProject (/node_modules/typescript/lib/typescript.js:188422:44)\n' +
        '    at _ProjectService.tryFindDefaultConfiguredProjectForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188446:25)\n' +
        '    at _ProjectService.tryFindDefaultConfiguredProjectAndLoadAncestorsForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188492:25)\n' +
        '    at _ProjectService.assignProjectToOpenedScriptInfo (/node_modules/typescript/lib/typescript.js:188377:27)\n' +
        '    at /node_modules/typescript/lib/typescript.js:188790:25\n' +
        '    at Array.forEach (<anonymous>)\n' +
        '    at _ProjectService.applyChangesInOpenFiles (/node_modules/typescript/lib/typescript.js:188788:56)\n' +
        '    at updateOpen (/node_modules/typescript/lib/typescript.js:189987:29)\n' +
        '    at /node_modules/typescript/lib/typescript.js:192655:15\n' +
        '    at IpcIOSession.executeWithRequestId (/node_modules/typescript/lib/typescript.js:192644:14)\n' +
        '    at IpcIOSession.executeCommand (/node_modules/typescript/lib/typescript.js:192653:29)\n' +
        '    at IpcIOSession.onMessage (/node_modules/typescript/lib/typescript.js:192701:68)\n' +
        '    at process.<anonymous> (/node_modules/typescript/lib/tsserver.js:525:14)\n' +
        '    at process.emit (node:events:519:28)\n' +
        '    at emit (node:internal/child_process:951:14)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)',
      _serverType: 'semantic'
    },
    serverMessage: 'Debug Failure.',
    serverStack: 'Error: Debug Failure.\n' +
      '    at _ProjectService.updateNonInferredProjectFiles (/node_modules/typescript/lib/typescript.js:187453:34)\n' +
      '    at _ProjectService.addFilesToNonInferredProject (/node_modules/typescript/lib/typescript.js:187223:10)\n' +
      '    at _ProjectService.updateRootAndOptionsOfNonInferredProject (/node_modules/typescript/lib/typescript.js:187498:10)\n' +
      '    at _ProjectService.loadConfiguredProject (/node_modules/typescript/lib/typescript.js:187299:10)\n' +
      '    at _ProjectService.reloadConfiguredProject (/node_modules/typescript/lib/typescript.js:187548:10)\n' +
      '    at ConfiguredProject2.updateGraph (/node_modules/typescript/lib/typescript.js:185430:29)\n' +
      '    at updateWithTriggerFile (/node_modules/typescript/lib/typescript.js:185927:11)\n' +
      '    at updateConfiguredProject (/node_modules/typescript/lib/typescript.js:185935:9)\n' +
      '    at _ProjectService.findCreateOrReloadConfiguredProject (/node_modules/typescript/lib/typescript.js:188422:44)\n' +
      '    at _ProjectService.tryFindDefaultConfiguredProjectForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188446:25)\n' +
      '    at _ProjectService.tryFindDefaultConfiguredProjectAndLoadAncestorsForOpenScriptInfo (/node_modules/typescript/lib/typescript.js:188492:25)\n' +
      '    at _ProjectService.assignProjectToOpenedScriptInfo (/node_modules/typescript/lib/typescript.js:188377:27)\n' +
      '    at /node_modules/typescript/lib/typescript.js:188790:25\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at _ProjectService.applyChangesInOpenFiles (/node_modules/typescript/lib/typescript.js:188788:56)\n' +
      '    at updateOpen (/node_modules/typescript/lib/typescript.js:189987:29)\n' +
      '    at /node_modules/typescript/lib/typescript.js:192655:15\n' +
      '    at IpcIOSession.executeWithRequestId (/node_modules/typescript/lib/typescript.js:192644:14)\n' +
      '    at IpcIOSession.executeCommand (/node_modules/typescript/lib/typescript.js:192653:29)\n' +
      '    at IpcIOSession.onMessage (/node_modules/typescript/lib/typescript.js:192701:68)\n' +
      '    at process.<anonymous> (/node_modules/typescript/lib/tsserver.js:525:14)\n' +
      '    at process.emit (node:events:519:28)\n' +
      '    at emit (node:internal/child_process:951:14)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)',
    sanitizedStack: 'suppressed.js:187453:34\n' +
      'suppressed.js:187223:10\n' +
      'suppressed.js:187498:10\n' +
      'suppressed.js:187299:10\n' +
      'suppressed.js:187548:10\n' +
      'suppressed.js:185430:29\n' +
      'suppressed.js:185927:11\n' +
      'suppressed.js:185935:9\n' +
      'suppressed.js:188422:44\n' +
      'suppressed.js:188446:25\n' +
      'suppressed.js:188492:25\n' +
      'suppressed.js:188377:27\n' +
      'suppressed.js:188790:25\n' +
      'suppressed.js:188788:56\n' +
      'suppressed.js:189987:29\n' +
      'suppressed.js:192655:15\n' +
      'suppressed.js:192644:14\n' +
      'suppressed.js:192653:29\n' +
      'suppressed.js:192701:68\n' +
      'tsserver.js:525:14\n'
  }
} 
```

**Comment by jtubbenhauer** [comment]
This has been bugging me. For a dirty fix I'm using:

```
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = "diffview://*",
  callback = function()
    vim.b.coc_enabled = false
  end,
})
```

**Comment by jtubbenhauer** [comment]
> `b.coc_enabled = false` can be used, but it will disable buffer related features from coc.nvim.

Yes I should have mentioned that in my suggestion. For my use case this is fine as I don't require LSP integration when viewing diffs.
