### ISSUE TITLE
Unable to "go to definition" for anything installed to node_modules when using jumpCommand of `tab drop`

### ISSUE THREAD

**Issue by ohjames** [neoclide/coc-tsserver#74]
This only happens when I set:

`"coc.preferences.jumpCommand": "tab drop"`

I enabled debugging and I see this:

```
manager.ts:720 Error: request error nvim_call_function - Vim(drop):E479: No match
    at /home/james/.local/share/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
    at NvimTransport.parseMessage (/home/james/.local/share/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:57:17)
    at DecodeStream.<anonymous> (/home/james/.local/share/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:27:18)
    at DecodeStream.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at DecodeStream.push (_stream_readable.js:220:10)
    at DecodeStream.push (_stream_transform.js:150:32)
    at DecodeBuffer.push (/home/james/.local/share/nvim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
    at DecodeBuffer.flush (/home/james/.local/share/nvim/plugged/coc.nvim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)
```

I can "go to definition" for any local symbols, but it won't work for anything installed to `node_modules`. Tried across many projects, always the same. Seems to work when not using `tab drop`.

**Comment by ohjames** [comment]
I changed to `tabe` for now.

**Comment by ohjames** [comment]
Actually it would be nice to use custom commands for this also... I prefer to use the `TabDrop` extension to vim's `tab drop` which has many issues with events.

**Comment by ohjames** [comment]
e.g. check out this serious issue with `tab drop`: https://github.com/vim/vim/issues/1660

**Comment by chemzqm** [comment]
You should check your wildignore option

**Comment by ohjames** [comment]
Why would `wildignore` affect `tab drop` but not `tabe`? Wouldn't it be nice to be able to `tab drop` the `node_modules` via "go to definition" without having to also grep through them?

**Comment by chemzqm** [comment]
No idea, it's vim's problem.

**Comment by ohjames** [comment]
It only accepts a limited set of possibilities, it won't let you configure generic handlers. Ideally I wanna use :TabDrop

**Comment by chemzqm** [comment]
You can ignore that warning, fixed on master of coc.nvim.
